/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationTokenResponse } from '../../models/application-token-response';
import { TokenRequest } from '../../models/token-request';

export interface UserTokenService$Params {
      body: TokenRequest
}

export function userTokenService(http: HttpClient, rootUrl: string, params: UserTokenService$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, userTokenService.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationTokenResponse>;
    })
  );
}

userTokenService.PATH = '/auth/refresh-token';
