services:
  database:
    container_name: budgettrackerdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budgettracker
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_budgettracker:/var/lib/postgresql/data/ 

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE=trial
    restart: unless-stopped
    ports:
      - "4002:80"
    volumes:
      - seq_storage:/data

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5001:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro