/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetAccountByIdResponse } from '../../models/get-account-by-id-response';

export interface GetAccountById$Params {
  id: string;
}

export function getAccountById(http: HttpClient, rootUrl: string, params: GetAccountById$Params, context?: HttpContext): Observable<StrictHttpResponse<GetAccountByIdResponse>> {
  const rb = new RequestBuilder(rootUrl, getAccountById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetAccountByIdResponse>;
    })
  );
}

getAccountById.PATH = '/account/{id}';
