/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageableResponseOfSearchAccountResponse } from '../../models/pageable-response-of-search-account-response';
import { SearchAccountRequest } from '../../models/search-account-request';

export interface SearchAccount$Params {
      body: SearchAccountRequest
}

export function searchAccount(http: HttpClient, rootUrl: string, params: SearchAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<PageableResponseOfSearchAccountResponse>> {
  const rb = new RequestBuilder(rootUrl, searchAccount.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageableResponseOfSearchAccountResponse>;
    })
  );
}

searchAccount.PATH = '/account/search';
