/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TokenResponse } from '../models/token-response';
export type ApplicationTokenResponse = TokenResponse & {
};
