/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthRegisterRequest {
  confirmPassword?: string;
  email: string;
  password: string;
}
