/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransactionRequest {
  accountId: string;
  amount: number;
  date: string;
  description: string;
}
