/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionDirectionEnum } from '../models/transaction-direction-enum';
export interface GetTransactionByIdResponse {
  accountId?: string;
  amount?: number;
  date?: string;
  dateCreated?: string;
  description?: string;
  direction?: TransactionDirectionEnum;
  id?: string;
}
