/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetAccountByIdResponse {
  dateCreated?: string;
  id?: string;
  name?: string;
  userId?: number;
}
