/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDirectionEnum } from '../models/order-direction-enum';
export interface PageableRequest {
  orderBy?: string;
  orderDirection?: OrderDirectionEnum;
  pageNumber?: number;
  pageSize?: number;
}
