/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDirectionEnum } from '../models/order-direction-enum';
import { SeachTransactionResponse } from '../models/seach-transaction-response';
export interface PageableResponseOfSeachTransactionResponse {
  data?: Array<SeachTransactionResponse>;
  orderBy?: string;
  orderDirection?: OrderDirectionEnum;
  pageCount?: number;
  pageNumber?: number;
  pageSize?: number;
  totalRecords?: number;
}
