/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateRange } from '../models/date-range';
import { PageableRequest } from '../models/pageable-request';
import { TransactionDirectionEnum } from '../models/transaction-direction-enum';
export type SeachTransactionRequest = PageableRequest & {
'accountId'?: string | null;
'transactionDirection'?: TransactionDirectionEnum | null;
'dateRange'?: DateRange | null;
};
