/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageableRequest } from '../models/pageable-request';
export type SearchTagRequest = PageableRequest & {
};
