/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TokenRequest } from '../models/token-request';
export type TokenResponse = TokenRequest & {
'accessToken'?: string;
};
