/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTransactionRequest {
  amount: number;
  date: string;
  description: string;
  id: string;
}
