name: Budget Tracker CI Pipeline

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:


# Add this permissions block at the top level
permissions:
  contents: read
  checks: write    # Required for test reporter to create check runs

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./BudgetTracker.sln
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test with coverage
      run: |
        for project in $(find . -name "*Tests.csproj" -o -name "*Test.csproj"); do
          projectName=$(basename "$project" .csproj)
          echo "Running tests for $projectName"
          dotnet test "$project" --no-build --verbosity normal --logger "trx;LogFileName=$projectName.trx" --collect:"XPlat Code Coverage" --results-directory ./TestResults
        done
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: xUnit Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
    
    - name: Generate coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"./TestResults/**/coverage.cobertura.xml" -targetdir:"./TestResults/CoverageReport" -reporttypes:"Html;Cobertura"
    
    - name: Publish coverage report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./TestResults/CoverageReport/Cobertura.xml
        badge: true
        format: markdown
        output: both
        
    - name: Add coverage PR comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./TestResults
        fail_ci_if_error: false
        verbose: true
        
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./TestResults
        retention-days: 30
        
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./TestResults/CoverageReport
        retention-days: 30